{% set name = "flake8-variables-names" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_variables_names-{{ version }}.tar.gz
  sha256: 292c50e4813d632aa3adcd02c185e7bb583f5fc8ebe02e70f13c958bfe46ad91

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - flake8_variables_names
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/best-doctor/flake8-variables-names
  summary: A flake8 extension that helps to make more readable variables names
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
